AWSTemplateFormatVersion: 2010-09-09
Resources:
  DLIUCOM:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: dliu.com

Outputs:
  HostedZoneId:
    Description: The ID of dliu.com hosted zone
    Value: !Ref DLIUCOM
    Export:
      Name: DLIUCOMHostedZoneID