AWSTemplateFormatVersion: 2010-09-09
Description: ATTENTION! This file contains important DNS configurations.
Parameters:
  MainDomain:
    Type: String
    Default: dliu.com
Resources:
  MainHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref MainDomain

  DNSSEC:
    Type: AWS::Route53::DNSSEC
    Properties:
      HostedZoneId: !Ref MainHostedZone
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    DependsOn:
      - "DNSSECKSK"

  DNSSECKSK:
    Type: AWS::Route53::KeySigningKey
    Properties:
      HostedZoneId: !Ref MainHostedZone
      Name: default_ksk
      Status: ACTIVE
      KeyManagementServiceArn: !Join
        - ""
        - - "arn:aws:kms:us-east-1:"
          - !Ref AWS::AccountId
          - ":alias/default-dnssec-ksk"
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete

Outputs:
  MainHostedZoneId:
    Description: Main Hosted Zone ID
    Value: !Ref MainHostedZone
    Export:
      Name: MainHostedZoneId
  
  MainDomain:
    Description: Main Domain Name
    Value: !Ref MainDomain
    Export:
      Name: MainDomain

