AWSTemplateFormatVersion: 2010-09-09
Description: ATTENTION! This file contains important DNS configurations.
Resources:
  DLIUCOM:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: dliu.com

  DNSSEC:
    Type: AWS::Route53::DNSSEC
    Properties:
      HostedZoneId: !ImportValue DLIUCOMHostedZoneID
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete

  DNSSECKSK:
    Type: AWS::Route53::KeySigningKey
    Properties:
      HostedZoneId: !ImportValue DLIUCOMHostedZoneID
      Name: default_ksk
      Status: ACTIVE
      KeyManagementServiceArn: !Join
        - ""
        - - "arn:aws:kms:us-east-1:"
          - !Ref AWS::AccountId
          - ":alias/default-dnssec-ksk"
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete

Outputs:
  HostedZoneId:
    Description: The Hosted Zone ID of dliu.com
    Value: !Ref DLIUCOM
    Export:
      Name: DLIUCOMHostedZoneID
