AWSTemplateFormatVersion: 2010-09-09
Resources:
  DLIUCOM:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: dliu.com

  WildcardRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref DLIUCOM
      Name: "*.dliu.com"
      Type: CNAME
      TTL: "3600"
      ResourceRecords:
        - "dliu.com"

Outputs:
  HostedZoneId:
    Description: The Hosted ID of dliu.com
    Value: !Ref DLIUCOM
    Export:
      Name: DLIUCOMHostedZoneID