AWSTemplateFormatVersion: 2010-09-09
Resources:
  DLIUCOM:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: dliu.com

Outputs:
  HostedZoneId:
    Description: The Hosted ID of dliu.com
    Value: !Ref DLIUCOM
    Export:
      Name: DLIUCOMHostedZoneID