AWSTemplateFormatVersion: 2010-09-09
Description: ATTENTION! This file contains important DNS configurations
Resources:
  DLIUCOM:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: dliu.com

Outputs:
  HostedZoneId:
    Description: The Hosted Zone ID of dliu.com
    Value: !Ref DLIUCOM
    Export:
      Name: DLIUCOMHostedZoneID