pipeline {
    agent {
        label 'deployer-slave-amazon-linux'
    }

    options {
        timeout(time: 10, unit: 'MINUTES')
    }

    stages {
        stage('Update Hosted Zone') {
            steps {
                dir('hosted-zone'){
                    sh '''
                        aws cloudformation update-stack --region eu-west-2 --stack-name DNS --template-body file://cloudformation.yml --tags Key=service,Value=dns;
                        aws cloudformation wait stack-update-complete --region eu-west-2 --stack-name DNS;
                    '''
                }
            }
        }
    }
}
