AWSTemplateFormatVersion: 2010-09-09
Description: ATTENTION! This file contains important DNS configurations
Resources:
  MicrosoftBusinessMXRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !ImportValue DLIUCOMHostedZoneID
      Name: dliu.com
      Type: MX
      TTL: "3600"
      ResourceRecords:
        - 0 dliu-com.mail.protection.outlook.com

  MicrosoftBusinessCNameRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !ImportValue DLIUCOMHostedZoneID
      Name: autodiscover.dliu.com
      Type: CNAME
      TTL: "3600"
      ResourceRecords:
        - autodiscover.outlook.com

  MicrosoftBusinessTXTRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !ImportValue DLIUCOMHostedZoneID
      Name: dliu.com
      Type: TXT
      TTL: "3600"
      ResourceRecords:
        # Microsoft Exchange SPF
        - '"v=spf1 include:spf.protection.outlook.com ~all"'
        # Google search verification
        - '"google-site-verification=xCP_ZUQTjQReN0xhcagY6pTSi12Y1jIuNGeEUWzPRSg"'

  MicrosoftBusinessDkimRecord1:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !ImportValue DLIUCOMHostedZoneID
      Name: selector1._domainkey.dliu.com
      Type: CNAME
      TTL: "3600"
      ResourceRecords:
        - selector1-dliu-com._domainkey.deweiliu.onmicrosoft.com

  MicrosoftBusinessDkimRecord2:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !ImportValue DLIUCOMHostedZoneID
      Name: selector2._domainkey.dliu.com
      Type: CNAME
      TTL: "3600"
      ResourceRecords:
        - selector2-dliu-com._domainkey.deweiliu.onmicrosoft.com

  MicrosoftBusinessDmarcRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !ImportValue DLIUCOMHostedZoneID
      Name: _dmarc.dliu.com
      Type: TXT
      TTL: "3600"
      ResourceRecords:
        # DMARC record defaults: pct=100; rf=afrf;
        - '"v=DMARC1; p=quarantine; fo=1; rua=mailto:dmarc-failure@dliu.com;"'

  MicrosoftSkypeServiceRecord1:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !ImportValue DLIUCOMHostedZoneID
      Name: sip.dliu.com
      Type: CNAME
      TTL: "3600"
      ResourceRecords:
        - sipdir.online.lync.com.

  MicrosoftSkypeServiceRecord2:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !ImportValue DLIUCOMHostedZoneID
      Name: lyncdiscover.dliu.com
      Type: CNAME
      TTL: "3600"
      ResourceRecords:
        - webdir.online.lync.com.

  MicrosoftSkypeServiceRecord3:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !ImportValue DLIUCOMHostedZoneID
      Name: _sip._tls.dliu.com
      Type: SRV
      TTL: "3600"
      ResourceRecords:
        - 100 1 443 sipdir.online.lync.com.

  MicrosoftSkypeServiceRecord4:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !ImportValue DLIUCOMHostedZoneID
      Name: _sipfederationtls._tcp.dliu.com
      Type: SRV
      TTL: "3600"
      ResourceRecords:
        - 100 1 5061 sipfed.online.lync.com.

  WildcardRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !ImportValue DLIUCOMHostedZoneID
      Name: "*.dliu.com"
      Type: CNAME
      TTL: "3600"
      ResourceRecords:
        - "dliu.com"
